[package]
name = "umls"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
hex-literal = "0.4.1"
hybrid-array = "0.2.3"

[features]
x25519_aes128gcm_ed25519 = []
default = ["x25519_aes128gcm_ed25519"]
